export const MOCK_PRODUCTS_DATA = [
    {
        name: "Atlantic Salmon Fillet",
        category: "Fish",
        price: 24.99,
        image: "/fresh-fish-and-meat-premium-quality.jpg",
        rating: 4.8,
        reviews: 156,
        tag: "Premium",
        description: "Premium quality Atlantic salmon fillets, sustainably sourced and fresh daily.",
        weight: "1 lb",
    },
    {
        name: "Grass-Fed Beef Steak",
        category: "Meat",
        price: 32.99,
        image: "/grass-fed-beef-steak-premium.jpg",
        rating: 4.9,
        reviews: 203,
        tag: "Bestseller",
        description: "Tender grass-fed beef steaks from local farms, perfect for grilling.",
        weight: "12 oz",
    },
    {
        name: "Sea Bass Fillet",
        category: "Fish",
        price: 28.99,
        image: "/fresh-sea-bream-whole-fish.jpg",
        rating: 4.7,
        reviews: 128,
        tag: "New",
        description: "Fresh sea bass fillets with delicate flavor, perfect for pan-searing.",
        weight: "1 lb",
    },
    {
        name: "Lamb Chops",
        category: "Meat",
        price: 26.99,
        image: "/premium-lamb-chops-fresh.jpg",
        rating: 4.8,
        reviews: 94,
        tag: "Fresh",
        description: "Tender lamb chops from grass-fed sheep, perfect for special occasions.",
        weight: "8 oz",
    },
    {
        name: "Wild Caught Tuna",
        category: "Fish",
        price: 34.99,
        image: "/wild-caught-tuna-premium.jpg",
        rating: 4.9,
        reviews: 167,
        tag: "Premium",
        description: "Premium wild-caught tuna steaks, rich in omega-3 fatty acids.",
        weight: "1.5 lbs",
    },
    {
        name: "Free-Range Chicken Breast",
        category: "Meat",
        price: 18.99,
        image: "/organic-free-range-chicken-breast.jpg",
        rating: 4.6,
        reviews: 245,
        tag: "Popular",
        description: "Tender, organic free-range chicken breasts, hormone-free.",
        weight: "2 lbs",
    },
    {
        name: "Norwegian Arctic Cod",
        category: "Fish",
        price: 22.99,
        image: "fresh-sea-bream-whole-fish.jpg",
        rating: 4.7,
        reviews: 112,
        tag: "Sustainable",
        description: "Pure white cod from Norwegian waters, sustainably caught.",
        weight: "1 lb",
    },
    {
        name: "Prime Ribeye Steak",
        category: "Meat",
        price: 45.99,
        image: "/placeholder.svg?key=04",
        rating: 4.9,
        reviews: 189,
        tag: "Premium",
        description: "Prime ribeye steaks with marbling for maximum flavor.",
        weight: "16 oz",
    },
    {
        name: "Fresh Shrimp",
        category: "Seafood",
        price: 19.99,
        image: "/placeholder.svg?key=05",
        rating: 4.7,
        reviews: 143,
        tag: "Fresh",
        description: "Jumbo fresh shrimp, perfect for pasta or grilling.",
        weight: "1 lb",
    },
    {
        name: "Heritage Pork Chops",
        category: "Meat",
        price: 21.99,
        image: "/placeholder.svg?key=06",
        rating: 4.8,
        reviews: 98,
        tag: "Natural",
        description: "Heritage breed pork chops, naturally raised without antibiotics.",
        weight: "1 lb",
    },
    {
        name: "Fresh Mussels",
        category: "Seafood",
        price: 16.99,
        image: "/placeholder.svg?key=07",
        rating: 4.6,
        reviews: 76,
        tag: "Fresh",
        description: "Fresh live mussels, perfect for pasta or seafood dishes.",
        weight: "2 lbs",
    },
    {
        name: "Wagyu Beef Ground",
        category: "Meat",
        price: 38.99,
        image: "/placeholder.svg?key=08",
        rating: 4.9,
        reviews: 134,
        tag: "Premium",
        description: "Premium Wagyu ground beef with exceptional marbling.",
        weight: "1 lb",
    },
];

export const MOCK_PRODUCT_DETAILS = {
    price: 24.99,
    stock: 156,
    sku: "CKN-BRST-001",
    rating: 4.8,
    reviews: 124,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-20T14:30:00Z",
    status: "In Stock",
    views: 1205
};

export const DUMMY_ABOUT_US = [
    {
        id: "1",
        title: "Our Story",
        content: "Culinary Fresh started with a simple mission: to bring the freshest ingredients to your kitchen.",
        image_url: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&q=80&w=1000",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    },
    {
        id: "2",
        title: "Our Mission",
        content: "To support local farmers and provide sustainable food options.",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
    }
];

export const DUMMY_CONTACT_US = [
    {
        id: "1",
        name: "John Doe",
        email: "john@example.com",
        message: "I have a question about bulk orders.",
        status: "pending",
        created_at: new Date().toISOString()
    },
    {
        id: "2",
        name: "Jane Smith",
        email: "jane@example.com",
        phone: "+1 234 567 8900",
        message: "Can I return a product?",
        status: "responded",
        created_at: new Date(Date.now() - 86400000).toISOString()
    }
];
